services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
      - wp_socket:/run/php
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - wp_socket:/run/php
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vboxuser/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vboxuser/data/wordpress
      o: bind

  wp_socket:
    driver: local
    driver_opts:
      type: none
      device: /home/vboxuser/data/wp_socket
      o: bind

networks:
  inception:
    driver: bridge
