services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception


  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
      - wp_socket:/run/php
    networks:
      - inception

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - wp_socket:/run/php
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:
  wp_socket:

networks:
  inception:
    driver: bridge
